<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="home-VAIO" ignored="3" name="Default test" tests="2" failures="1" timestamp="04 Jun 2020 11:21:16 GMT" time="19.262" errors="0">
  <testcase name="openRemedyTest" time="10.872" classname="com.test.TC_RemedyIncident_Creation"/>
  <testcase name="test_createInc" time="2.078" classname="com.test.TC_RemedyIncident_Creation">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: test_createInc([Parameter{index=0, type=java.util.ArrayList, declaredAnnotations=[]}, Parameter{index=1, type=com.aventstack.extentreports.ExtentTest, declaredAnnotations=[]}])
Arguments: [(java.util.ArrayList) [Yes, TELEFONICA UK, birajds1, test, dummy testing, 3-Moderate/Limited, 3-Medium, User Service Restoration, TELEFONICA UK, Networks - Network Operations - G-NOC RAN, Field Services, smart metering, cnbas-esxvm-345.uk.pri.o2.com, Field Services Auto-Resolver, RAN, Build, , Business Service, Customer Facing, , , , INC000000507662]]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: test_createInc([Parameter{index=0, type=java.util.ArrayList, declaredAnnotations=[]}, Parameter{index=1, type=com.aventstack.extentreports.ExtentTest, declaredAnnotations=[]}])
Arguments: [(java.util.ArrayList) [Yes, TELEFONICA UK, birajds1, test, dummy testing, 3-Moderate/Limited, 3-Medium, User Service Restoration, TELEFONICA UK, Networks - Network Operations - G-NOC RAN, Field Services, smart metering, cnbas-esxvm-345.uk.pri.o2.com, Field Services Auto-Resolver, RAN, Build, , Business Service, Customer Facing, , , , INC000000507662]]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:983)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_createInc -->
  <testcase name="test_searchIncDetails" time="0.0" classname="com.test.TC_RemedyIncident_Creation">
    <ignored/>
  </testcase> <!-- test_searchIncDetails -->
  <testcase name="test_updateInc" time="0.0" classname="com.test.TC_RemedyIncident_Creation">
    <ignored/>
  </testcase> <!-- test_updateInc -->
  <testcase name="test_AddCI" time="0.0" classname="com.test.TC_RemedyIncident_Creation">
    <ignored/>
  </testcase> <!-- test_AddCI -->
</testsuite> <!-- Default test -->
