<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="TECHMASST300004" name="com.test.TC_NetCoolRemedyInc" tests="3" failures="1" timestamp="2020-08-25T11:31:21 IST" time="38.944" errors="0">
  <testcase name="openRemedyTest" time="7.085" classname="com.test.TC_NetCoolRemedyInc"/>
  <system-out/>
  <testcase name="test_NetcoolIncident" time="31.859" classname="com.test.TC_NetCoolRemedyInc">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [TELEFONICA UK1] but found [TELEFONICA UK]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [TELEFONICA UK1] but found [TELEFONICA UK]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.java.Inc_Utility.verifyNetcoolIncDetails(Inc_Utility.java:1195)
at com.test.TC_NetCoolRemedyInc.test_NetcoolIncident(TC_NetCoolRemedyInc.java:83)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_NetcoolIncident -->
  <system-out/>
  <testcase name="test_NetcoolIncidentData" classname="com.test.TC_NetCoolRemedyInc">
    <skipped/>
  </testcase> <!-- test_NetcoolIncidentData -->
  <system-out/>
</testsuite> <!-- com.test.TC_NetCoolRemedyInc -->
